team_variations = {
    "Atlanta Hawks": ["Hawks", "Atlanta"],
    "Boston Celtics": ["Celtics", "Boston"],
    "Brooklyn Nets": ["Nets", "Brooklyn"],
    "Charlotte Hornets": ["Hornets", "Charlotte"],
    "Chicago Bulls": ["Bulls", "Chicago"],
    "Cleveland Cavaliers": ["Cavs", "Cavaliers", "Cleveland"],
    "Dallas Mavericks": ["Mavericks", "Dallas", "Mavs"],
    "Denver Nuggets": ["Nuggets", "Denver"],
    "Detroit Pistons": ["Pistons", "Detroit"],
    "Golden State Warriors": ["Warriors", "Dubs", "Golden State"],
    "Houston Rockets": ["Rockets", "Houston"],
    "Indiana Pacers": ["Pacers", "Indiana"],
    "Los Angeles Clippers": ["Clippers", "Clips"],
    "Los Angeles Lakers": ["Lakers"],
    "Memphis Grizzlies": ["Grizzlies", "Memphis"],
    "Miami Heat": ["Heat", "Miami"],
    "Milwaukee Bucks": ["Bucks", "Milwaukee"],
    "Minnesota Timberwolves": ["Timberwolves", "Wolves", "Minnesota"],
    "New Orleans Pelicans": ["Pelicans", "Pels", "New Orleans"],
    "New York Knicks": ["Knicks", "New York"],
    "Oklahoma City Thunder": ["Thunder", "OKC", "Oklahoma City"],
    "Orlando Magic": ["Magic", "Orlando"],
    "Philadelphia 76ers": ["76ers", "Sixers", "Philadelphia"],
    "Phoenix Suns": ["Suns", "Phoenix"],
    "Portland Trail Blazers": ["Trail Blazers", "Blazers", "Portland"],
    "Sacramento Kings": ["Kings", "Sacramento"],
    "San Antonio Spurs": ["Spurs", "San Antonio"],
    "Toronto Raptors": ["Raptors", "Toronto"],
    "Utah Jazz": ["Jazz", "Utah"],
    "Washington Wizards": ["Wizards", "Washington"],
}

player_exceptions = [
    "Mathews", "Matthews", "Chalmers", "Favors", "Flowers", "Livers", "Rivers",
    "Travers", "Waters", "Waiters", "Fitts", "Betts", "Phillips", "Poythress",
    "Ross", "Williams-Goss", "Jenkins", "Harkless", "Chriss", "Bass", "Bayless",
    "Edwards", "Hands", "Ponds", "Reynolds", "Suggs", "Kammerichs", "Hannahs",
    "Pasecniks", "Meeks", "Hicks", "Hendricks", "Franks", "Eubanks", "Cooks",
    "Brooks", "Burks", "Banks", "Daniels", "Keels", "Mills", "McDaniels",
    "Samuels", "Wills", "Wells", "Mays", "Days", "Kurucs", "Wiggins", "Towns",
    "Simmons", "Simons", "Stephens", "Rollins", "Robbins", "Pons", "Parsons",
    "Owens", "Noel", "McGowens", "Leons", "Kurucs", "Jenkins", "Hawkins",
    "Hudgins", "Hagans", "Evans", "Cousins", "Clemons", "Collins", "Cousins",
    "Bertans", "Burns", "Blevins", "Alkins", "Arms", "Adams", "Carter-Williams",
    "Simms", "Sims", "Williams", "Weems"
]
